development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ooxsaawidyxrbw:pHx26_Ovp8jyekRJYt6vFVxODm@ec2-54-243-249-132.compute-1.amazonaws.com:5432/d2kt7lsn22dk2v
